### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by imwithsam** [JoshCheek/atom-seeing-is-believing#17]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:265:11)
PackageManager.packageHasSettings (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:42:14)
PackageCard.hasSettings (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:612:34)
PackageCard.initialize (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
PackageCard.View (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
new PackageCard (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
```

**Comment by JoshCheek** [comment]
Yeah, I spent maybe 3 days trying to get this working back in January. There's a branch where I tried it, a bunch of issues I opened in Atom, and a bunch of notes over in Issue #12 It might be better now that they've released 1.0, but I'm allotting my time to https://github.com/JoshCheek/ruby_slippers_for_the_cobblers_children for now.

**Comment by imwithsam** [comment]
Interesting...have you set Ruby Slippers up with students at Turing yet?

**Comment by JoshCheek** [comment]
It's not good enough yet. I got it rendering at one point, but then switched languages to JavaScript. I've been working on it a fair amount over the break though. Hoping to have it for my August class. I expect to have it interpreting my acceptance test within a day or two, and then it becomes a question of how to draw these things, which could take 1 to 2 weeks to figure out (best guess right now: React + Paper.js or Processing.js, but when I dream, it's three.js ^_^)
