### ISSUE TITLE
Can I use this with Python in Atom.io

### ISSUE THREAD

**Issue by abrar2741** [JoshCheek/atom-seeing-is-believing#20]
If yes, then please show me how? I got ruby installed and also got seeing is believing gem installed. Now what should I do. I am not a pro in programming still wan to learn. Please help. :-)

**Comment by JoshCheek** [comment]
Unfortunately, it won't work with Python. It works by parsing the code and rewriting it with additional code to capture the results of each line, but not affect behaviour. The rewritten code is then run in a separate process where the environment is setup to allow for capturing things like printing. The line-result code also writes the events it sees to a file descriptor, which is sent back to the main process.

So, to make it work with Python, I'd probably have to change certain assumptions within the structure of Seeing Is Believing, as well as figure out how to rewrite Python, and enough about how Python works to be able to fake out the environment sufficiently. Unfortunately, that's very nontrivial, and I've used Python so infrequently, that there's very little incentive to work on such a thing (if I were going to do something like that, I'd probably try to do it for JavaScript).

**Comment by abrar2741** [comment]
@JoshCheek Thanks
